spring:
  datasource:
  url: jdbc:h2:~/testdb
  username: sa
  password: '{cipher}AQA3tGKUhHHzqJZEj3zrdx8hTgrf5HRobmZ45MarhzkKugUc7w2HUp8quQbEcMrZI9K74/bMix8/r6WDFeEe6YqKU1Dwa+CfYx7ktxNmamng+L4Q37Ilu+RCcFkhwzTvlcVeHGJKMXwahOA7Pl/OMvP20rMek+52xrx9PtVAhah43CAN4g4pvgFTMJslAq5PlOw/Kgr3s57sgE8qBf07Cr5UJhhzDOvfPkFgNu9lHsxQQBk8XjonhrTNyJfz+UgLF6AtpPSb4IiB5HT0KH9FbT3TzvntwAYnqoilXP8BbjeCEYnwI7jyZ0aRbJGQHskPnYUnHhFaZRt3UY3w/dNKh+plUvoWuZj+1ITCAMga8+X+UdNNDN3ML+7SHcTpliDGx+U='
  driver-class-name: org.h2.Driver


token:
  expiration_time: 86400000 #1day
  secret: saechimdaekiDevTokenabcdefghijklmnopqrstuvwxyz

gateway:
  ip: 192.168.200.152 # my ip..   

order_service:
  url: http://order-service/order-service/%s/orders   